In [1]:
import torch

In [4]:
A = torch.tensor([[2, 3],[7, 9],])
B = torch.tensor([[10, 1],[8, 6],])

In [ ]:
matmul1 = torch.matmul(A ,B) # Para multiplicação matricial é necessário que os tensores tenham shapes iguais e de tamanho igual
matmul2 = A @ B
print(matmul1)
print(matmul2)

tensor([[ 44,  20],
        [142,  61]])
tensor([[ 44,  20],
        [142,  61]])


In [6]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [9]:
transpose = matrix.T
print(f"Shape Original: {matrix.shape}")
print(f"Shape transpose: {transpose.shape}")
print(transpose)

Shape Original: torch.Size([2, 3])
Shape transpose: torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## Reshape
Usando o reshape é possível remoldar o tensor, adquirindo o formato desejado.

In [ ]:
new_matrix = torch.rand(12)

In [ ]:
new_matrix.reshape(3, 4) # Note que ao fazer reshape, os valores devem ser multiplos

tensor([[0.4498, 0.3873, 0.5997, 0.8850],
        [0.2736, 0.5594, 0.7668, 0.0768],
        [0.4608, 0.9131, 0.6125, 0.6927]])

In [ ]:
new_matrix.reshape(2, 6) # 2 * 6 = 12

tensor([[0.4498, 0.3873, 0.5997, 0.8850, 0.2736, 0.5594],
        [0.7668, 0.0768, 0.4608, 0.9131, 0.6125, 0.6927]])

In [22]:
converted = new_matrix.reshape(2, 3, 2) # 2 * 2 * 3 = 12

## Flatten (achatar)

In [ ]:
converted.flatten() # Transforma um tensor em um tensor de linha única

tensor([0.4498, 0.3873, 0.5997, 0.8850, 0.2736, 0.5594, 0.7668, 0.0768, 0.4608,
        0.9131, 0.6125, 0.6927])

### Flatten a partir de dimensão específica

In [33]:
tensor = torch.ones(10, 3, 3)

In [34]:
tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [37]:
flat_1 = tensor.flatten(start_dim=1)
flat_1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
flat_2 = tensor.flatten(start_dim=2)
flat_2

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [39]:
squeezed_in = torch.randn(1, 3, 1, 4)
squeezed_in.shape

torch.Size([1, 3, 1, 4])

In [ ]:
squeezed = squeezed_in.squeeze() # O método squeeze serve para comprimir tensores
print(squeezed.shape)

torch.Size([3, 4])


In [46]:
unsqueezed = squeezed.unsqueeze(2)
unsqueezed.shape

torch.Size([3, 4, 1])

## Any e All
Any e All são operadores voltados para conectivos universais e exclusórios

In [63]:
tensor = torch.rand(3, 3).mul_(100).ceil_()
tensor

tensor([[ 3., 51., 95.],
        [87., 98., 33.],
        [82., 41., 93.]])

In [ ]:
any_greater = torch.any(tensor > 10) # Retorna True, pois existe ao menos um valor maior do que 10
any_greater

tensor(True)

In [ ]:
all_lower = torch.all(tensor < 10) # Retorna False, pois nem todos os valores são menores do que 10
all_lower

tensor(False)

In [ ]:
prod = tensor.prod() # Faz o produto de todos os valores
prod

tensor(1.2787e+15)