# GPU e CPU

In [6]:
import torch

### Verificando GPU

In [7]:
# Verifica se a CUDA está disponível (se existe)
torch.cuda.is_available()

True

In [8]:
# Conta a quantidade de dispositivos
torch.cuda.device_count()

1

In [9]:
# Verifica a quantidade máxima de memória alocada
torch.cuda.max_memory_allocated()

0

In [10]:
# Verificação da temperatura da GPU
torch.cuda.temperature()

45

In [17]:
# Definindo qual é o tipo de device para rodar a aplicação
device = "cuda" if torch.cuda.is_available() else "cpu"

### Criando tensores
Podemos usar a função ".to" para mover tensores para diferentestipos de dispositivos (cpu, cuda)\
Mas também é possível utilizar para mover modelos

In [15]:
# tensor na cpu
tensor_cpu = torch.tensor([1, 2, 3], device="cpu")
tensor_cpu, tensor_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [16]:
# tensor na gpu (É possível verificar em qual gpu está)
tensor_gpu = torch.tensor([1, 2, 3], device="cuda")
tensor_gpu, tensor_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [19]:
# Como mover um tensor para a GPU
tensor_movido = tensor_cpu.to(device)
tensor_movido, tensor_movido.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
# Como passar um tensor de uma GPU para a CPU
tensor_to_cpu = tensor_movido.cpu() # Isso é feito para evitar conflitos, visto que o tipo que está na GPU é diferente do tipo da CPU
tensor_to_cpu, tensor_to_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Adquire o nome do dispositivo atual
torch.cuda.get_device_name()

In [ ]:
# Adquirindo uma série de informações do cuda
var = torch.cuda.get_device_properties()
print(f"""
    Nome: {var.name}
    Memória Total: {var.total_memory / 1024 ** 3:.2f} Gb
    Temperatura: {torch.cuda.temperature()}ºC
""")