## Start
1. Create a random tensor with shape (7, 7).
2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
3. Set the random seed to 0 and do exercises 2 & 3 over again.
4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
7. Find the maximum and minimum values of the output of 7.
8. Find the maximum and minimum index values of the output of 7.
9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [1]:
import torch

/home/operador/Documentos/Estudos/Projetos/Python Studies/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


In [2]:
# 1. Create a random tensor with shape (7, 7).
tensor = torch.rand(7, 7)
tensor

tensor([[0.3247, 0.0089, 0.3598, 0.7327, 0.4549, 0.6244, 0.0171],
        [0.7747, 0.9023, 0.2214, 0.8028, 0.8688, 0.3534, 0.7255],
        [0.4066, 0.3790, 0.1535, 0.3382, 0.9798, 0.5889, 0.0480],
        [0.3014, 0.6903, 0.0088, 0.6476, 0.9413, 0.7330, 0.8606],
        [0.8336, 0.1300, 0.7011, 0.1578, 0.4145, 0.7679, 0.1380],
        [0.3793, 0.7371, 0.2789, 0.9685, 0.9319, 0.2534, 0.5885],
        [0.4298, 0.2411, 0.1429, 0.8496, 0.6172, 0.0295, 0.0195]])

In [25]:
# 2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

In [28]:
tensor_final = torch.mm(tensor_A, tensor_B.T)
tensor_final

tensor([[1.6839],
        [1.5681],
        [1.3070],
        [1.7494],
        [1.5548],
        [0.8173],
        [1.2174]])

In [101]:
# 3. Set the random seed to 0 and do exercises 2 & 3 over again.
SEED = 0

torch.manual_seed(SEED)
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

In [102]:
tensor_final = torch.mm(tensor_A, tensor_B.T)
tensor_final

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [98]:
# 4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda for this one). 
# If there is, set the GPU random seed to 1234.

SEED = 1234

# Manipulando a seed diretamente no CUDA ao invés de ser no torch.
torch.cuda.manual_seed(SEED)
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

tensor_final = torch.mm(tensor_A, tensor_B.T)
tensor_final

tensor([[1.4904],
        [2.1532],
        [2.0529],
        [1.9964],
        [1.5254],
        [2.2362],
        [2.9596]])

In [ ]:
# 5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

# Para os tensores serem os mesmos, deve-se definir isso antes de setar o tensor!
torch.manual_seed(1234)
tensor_A = torch.rand(2, 3)

torch.manual_seed(1234)
tensor_B = torch.rand(2, 3)

# Tensores iguais!
tensor_A, tensor_B, tensor_A == tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[True, True, True],
         [True, True, True]]))

In [125]:
# 6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
output = torch.mm(tensor_A, tensor_B.T)
output

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [126]:
# 7. Find the maximum and minimum values of the output of 7.
print(f"""
    Min: {output.min()}
    Min: {output.max()}
""")


    Min: 0.21611443161964417
    Min: 0.628727912902832



In [127]:
# 8. Find the maximum and minimum index values of the output of 7.
print(f"""
    Min: {output.argmin()}
    Min: {output.argmax()}
""")

# O resutado de argmin ou argmax vem como um indice em flatten!
output = output.flatten()
output[1], output[3]


    Min: 1
    Min: 3



(tensor(0.2161), tensor(0.6287))

In [129]:
# 9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed 
# to be left with a tensor of shape (10). Set the seed to 7 when you create it and 
# print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.cuda.manual_seed(7)
rand_tensor = torch.rand(1, 1, 1, 10)
formatted_tensor = torch.squeeze(rand_tensor)

In [130]:
rand_tensor, rand_tensor.shape

(tensor([[[[0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294,
            0.9665, 0.7399]]]]),
 torch.Size([1, 1, 1, 10]))

In [131]:
formatted_tensor, formatted_tensor.shape

(tensor([0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665,
         0.7399]),
 torch.Size([10]))