In [1]:
import torch

## Mexendo com GPU e dispositivos

In [3]:
print(f"CUDA Disponível: {torch.cuda.is_available()}")
print(f"Número de GPUs: {torch.cuda.device_count()}")

CUDA Disponível: True
Número de GPUs: 1


In [5]:
# Verificando qual é a placa de vídeo
if torch.cuda.is_available():
    print(f"{torch.cuda.get_device_name(0)}")

NVIDIA GeForce GTX 1650


### Como selecionar a CUDA

In [10]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Usando dispositivo: {device}")

Usando dispositivo: cuda


In [11]:
tensor = torch.rand(2, 3)

In [ ]:
tensor.device # Checando em qual dispositivo está o tensor

device(type='cpu')

In [19]:
tensor = tensor.to("cuda")
tensor.device

device(type='cuda', index=0)

### Arange

In [4]:
arange_tensor = torch.arange(1, 11)
arange_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# tensor like
zeros = torch.zeros_like(input=arange_tensor)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Multiplicação de Matrix


Ao fazer uma multiplicação simples, de um conjunto de valores por um valor, como 2. Todo o conjunto de valores é multiplicado por 2.\
Essa é chamada de "Multiplicação Escalar"

In [10]:
tensor = torch.tensor([[1, 2, 3], [2, 3, 4]])
print(f"Tensor normal: {tensor}")
print(f"Tensor dobrado: {tensor * 2}")

Tensor normal: tensor([[1, 2, 3],
        [2, 3, 4]])
Tensor dobrado: tensor([[2, 4, 6],
        [4, 6, 8]])


Essa é a multiplicação de Matrizes multidimencionais, onde devemos utilizar o "dot product", onde, cada linha da primeira matrix e multimpliacada por cada coluna da segunda matrix.
Fazer multiplicações usando o matmul é muito mais rápido do que fazer na "mão"

In [16]:
matrix_1 = torch.tensor([4, 6, 7])
matrix_2 = torch.tensor([9, 0, 7])

In [ ]:
# Multiplication using matmul
torch.matmul(matrix_1, matrix_2)

# It gonna take 252 microseconds

tensor(85)

In [ ]:
# Multiplication by hand
matrix_1[0] * matrix_2[0] + matrix_1[1] * matrix_2[1] + matrix_1[2] * matrix_2[2]

# It gonna take 1,95ms

tensor(85)

### Some rules for matrix multiplication
1. The __inner dimensions__ must match:
* (2, 3) @ (2, 3) won't work
* (3, 2) @ (2, 3) will work
* (2, 3) @ (3, 2) will work

2. The resulting matrix has the shape of the __outer dimensions__
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [28]:
tensor_A = torch.tensor([
    [4, 5,],
    [7, 8],
    [10, 11]])

tensor_B = torch.tensor([
    [3, 5],
    [2, 8],
    [1, 12]])

In [29]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [31]:
torch.mm(tensor_A, tensor_B) # Não é possível multiplicar um (2, 3) por um (2, 3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [33]:
# Usando o transpose é possível mudar o corpo de uma matriz
tensor_B

tensor([[ 3,  5],
        [ 2,  8],
        [ 1, 12]])

In [34]:
tensor_B.T

tensor([[ 3,  2,  1],
        [ 5,  8, 12]])

In [35]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 37,  48,  64],
        [ 61,  78, 103],
        [ 85, 108, 142]])

## How find the position of the min and max

In [45]:
tensor_1 = torch.tensor([ 80, 20, 0, 10, 30, 40, 50, 90, 60, 70])
tensor_1

tensor([80, 20,  0, 10, 30, 40, 50, 90, 60, 70])

In [ ]:
# Achando o argumento mínimo, ele está na posição 2
tensor_1.argmin()

tensor(2)

In [ ]:
# Achando o argumento máximo, ele está na posição 7
tensor_1.argmax()

tensor(7)

In [ ]:
# O método argsort retona os indices do tensor ordenados pela forma crescente
tensor_1.argsort()

tensor([2, 3, 1, 4, 5, 6, 8, 9, 0, 7])

In [ ]:
# Identifica posicionalmente no tensor onde estão os valores maiores do que 50
torch.argwhere(tensor_1 > 50).reshape(4) # Usei reshape para deixar mais interpretável

tensor([0, 7, 8, 9])

## Reshaping, stacking, squeezing and unsqueezing
* Reshaping - Transforms a tensor to the form wanted.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [75]:
x = torch.arange(1, 11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
# Add extra dim
x_reshaped = x.reshape(10, 1) 
x_reshaped

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [71]:
# A quantidade para reshape deve ser compatível com a quantidade de termos, ex: 5 * 2 = 10
print(f"Reshape 1: \n{x.reshape(2, 5)}\n")
print(f"Reshape 2: \n{x.reshape(5, 2)}")

Reshape 1: 
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

Reshape 2: 
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])


In [76]:
z = x.view(1, 10)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
# Ao alterar a view, também é alterada o tensor original
z[:, 0] = 5
z, x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [85]:
# Stacj tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [101]:
y = torch.zeros(3, 1)
y.shape, y.ndim

(torch.Size([3, 1]), 2)

In [ ]:
# Romove todas as dimenções com apenas uma dimensão
y_squeezed = torch.squeeze(y)
y_squeezed.shape, y_squeezed.ndim

(torch.Size([3]), 1)

In [ ]:
# Adiciona dimeções
y_pos_squeezed = y_squeezed.unsqueeze(dim=1)
y_pos_squeezed.shape, y_pos_squeezed.ndim

(torch.Size([3, 1]), 2)

In [114]:
y_pos_squeezed

tensor([[0.],
        [0.],
        [0.]])

In [117]:
# torch.permute
original_image = torch.rand(size=(224, 224, 3))
original_image.shape

torch.Size([224, 224, 3])

In [ ]:
# Com o permuted é possível fazer uma alteração da ordem do corpo do tensor
permuted_image = original_image.permute(2, 0, 1)

print(f"Shape anterior: {original_image.shape}")
print(f"Shape atual: {permuted_image.shape}")

Shape anterior: torch.Size([224, 224, 3])
Shape atual: torch.Size([3, 224, 224])


In [ ]:
# O valor muda para as duas variáveis, pois permuted é uma view, então ela compartilha a mesma memória que a variável original.

original_image[0, 0, 0] = 5
print(f"Valor original: {original_image[0, 0, 0]}")
print(f"Valor permutado: {permuted_image[0, 0, 0]}")

Valor original: 5.0
Valor permutado: 5.0


## Pytorch Seed
It's possible define the actually seed for randomness

In [ ]:
# Note que para setar o uma seed manual é necessário fazer isso para cada vez em que quiser usar, quase como um encapsulamento

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
x_tensor = torch.rand(2, 3)

torch.manual_seed(RANDOM_SEED)
y_tensor = torch.rand(2, 3)

In [124]:
x_tensor, y_tensor, x_tensor == y_tensor

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[True, True, True],
         [True, True, True]]))