# Torch

There is some 3 big erros when working with pyTorch:
1. Tensors with wrong dtype
2. Tensors with wrong shape
3. Tensor in the wrong device

In [6]:
import torch

In [ ]:
# Qualquer tipo primitivo de narray é feito com tensor de torch.
# É importante reparar nas nomenclaturas para também saber manipular.

scalar = torch.tensor(1)
scalar, scalar.shape, scalar.ndim

(tensor(1), torch.Size([]), 0)

In [10]:
vector = torch.tensor([1, 2])
vector[0], vector.shape, vector.ndim

(tensor(1), torch.Size([2]), 1)

In [13]:
MATRIX = torch.tensor([[1, 2, 3],
                       [2, 3, 4]])
MATRIX[0], MATRIX.shape, MATRIX.ndim

(tensor([1, 2, 3]), torch.Size([2, 3]), 2)

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR[0], TENSOR.shape, TENSOR.ndim

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([1, 3, 3]),
 3)

## Torch Random

### Torch Arange

In [ ]:
# Com o torch arage é possível criar tensores de sequências numéricas
torch.arange(1, 9)

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
# É possível também mudar o formato do tensor com o reshape
torch.arange(1, 9).reshape(1, 2, 4)

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])

In [17]:
# Também é possível criar tensores com passos diferentes
torch.arange(0, 100, 5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

### Torch zeros

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten, one_to_ten.dtype

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.int64)

In [ ]:
# Podemos criar tensores de valores X usando como base um outro tensor
zeros = torch.zeros_like(input=one_to_ten)
zeros, zeros.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.int64)

### Torch Empty

In [8]:
empty = torch.empty(2, 3)
empty

tensor([[3.0421e-40, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 3.4960e-41, 0.0000e+00]])

### Outros

In [10]:
linspace = torch.linspace(0, 1, 5)
linspace

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [ ]:
eye = torch.eye(5) # Matriz identidade
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### Torch Dtype Definitions

In [ ]:
# Mesmo adicionando o dtype como None, ainda assim, o pyTorch irá preencher os valores por padrão com torch.float32
float_32 = torch.tensor([1.0, 9.0, 6.0], dtype=None)
float_32, float_32.dtype

(tensor([1., 9., 6.]), torch.float32)

In [ ]:
float_16 = torch.arange(1, 10, dtype=torch.float16)
float_16, float_16.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16),
 torch.float16)

In [25]:
# You can change a tensor dtype using the code below
float_16 = float_32.type(torch.float16)
float_16, float_16.dtype

(tensor([1., 9., 6.], dtype=torch.float16), torch.float16)

## Tensor Attributes

In [14]:
tensor = torch.tensor([1, 2, 3])
tensor.shape, tensor.ndim

(torch.Size([3]), 1)

## Tensor Operations

In [ ]:
a = torch.tensor([1, 2, 3]) # O tamanho dos tensores devem ser iguais para ser possível fazer operações
b = torch.tensor([4, 5, 6])

In [21]:
add = a + b
print(add)

tensor([5, 7, 9])


In [17]:
sub = a - b
print(sub)

tensor([-3, -3, -3])


In [22]:
mul = a * b
print(mul)

tensor([ 4, 10, 18])


In [23]:
div = a / b
print(div)

tensor([0.2500, 0.4000, 0.5000])


In [24]:
pot = a ** b
print(pot)

tensor([  1,  32, 729])


### In_Place Operation
É possível aplicar operações diversas operações inplace

In [26]:
x = torch.rand((3, 3))

In [27]:
print(x.add_(5))

tensor([[5.4874, 5.8602, 5.8195],
        [5.2535, 5.8937, 5.8055],
        [5.5125, 5.0493, 5.9172]])


In [30]:
print(x.abs_())

tensor([[5.4874, 5.8602, 5.8195],
        [5.2535, 5.8937, 5.8055],
        [5.5125, 5.0493, 5.9172]])
