# Início
Esse código é voltado para realizar experiências dentros das bibliotecas python de manipulação de dados e outras funcionalidades.

In [1]:
import pandas as pd
import numpy as np
import json

## Estudos Numpy
Código voltado para o estudo do numpy e suas funcionalidades

### Criação de Arrays
Existem diversas maneiras de criar arrays ou matrizes em numpy, cada uma possui uma utilidade especifica e seu próprio caso de uso, por conta disso, é interessante saber para o que serve cada tipo de função.
Note que o numpy é extremamente voltado para o desempenho e otimização, nota-se que o numpy é muito utilizado para cálculos de matrizes, modelos inteligentes e outras aplicações voltadas a matemática.

In [2]:
# Array básico
a1 = np.array([1, 2, 3])

# Matriz
a2 = np.array([[1, 2, 3], [2, 4, 6]])

In [3]:
# Pode-se manipular os arrays do numpy exatamente como no python normal
print(a1)
print(a1[0:2])
print(a1[2])

[1 2 3]
[1 2]
3


In [4]:
print(a2, "\n")
print(a2[0:2], "\n")
print(a2[1][0:2], "\n")

[[1 2 3]
 [2 4 6]] 

[[1 2 3]
 [2 4 6]] 

[2 4] 



In [ ]:
# .zeros() cria uma matriz em somente com zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# .ones() cria uma matriz em somente com uns
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# .full() cria uma matriz somente com os valores passados no parâmetro
print(np.full((3, 3), 10))
print(np.full((3,), 2))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[2 2 2]


In [ ]:
# .eye() cria uma matriz identidade
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# arange() cria uma matriz de valores onde é passado um início, fim e passo
# Note que é mesmo valores incoerêntes irão resultar em um valor arredondado.
# Para valores negatuvos, é interessante perceber que o passo deve estar negativo também.
print(
    np.arange(10, 100, 5)
    )
print(
    np.arange(10, 101, 5)
    )
print(
    np.arange(0, -5, -1)
    )

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[ 0 -1 -2 -3 -4]


In [ ]:
# .linspace() cria uma matriz com os valores de ínicio (0) e fim (1) e a faixa de valores que estão dentre esses valores
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.empty((3, 3))

array([[4.89977828e-315, 6.89033253e-310, 8.93700357e+165],
       [3.29647219e-032, 1.39425663e+165, 1.08607281e-042],
       [2.62243084e+180, 1.00406537e-042, 1.27930850e+165]])

### Visualização de Arrays


In [67]:
ar = np.random.rand(3, 3)

In [68]:
ar

array([[0.73925468, 0.84634589, 0.89243136],
       [0.55979756, 0.1478793 , 0.11324153],
       [0.51144821, 0.11471659, 0.15138464]])

In [69]:
ar <= 0.5

array([[False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [71]:
ar[ar <= 0.5]

array([0.1478793 , 0.11324153, 0.11471659, 0.15138464])

### Manipulação de Arrays

In [ ]:
# Transforma o ndarray em 1D
# O flatten cria uma cópia dos dados originais
arr = np.array([[1, 2], [3, 4]])
arr.flatten()

array([1, 2, 3, 4])

In [ ]:
# Transforma o ndarray em 1D
# O reshape cria uma view dos dados
arr.reshape(-1)

array([1, 2, 3, 4])

In [75]:
np.sin(arr)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [76]:
np.exp(arr)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [77]:
np.log(arr)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [79]:
np.dot(arr, arr)

array([[ 7, 10],
       [15, 22]])

### Random
No numpy, os valores randômicos são fáceis de serem utilizados, abaixo alguns exemplos

In [ ]:
# Cria valores numéricos aleatórios dentro de uma distribuição uniforme
np.random.rand(3, 3)

array([[0.05645097, 0.66522249, 0.30518276],
       [0.19639647, 0.56115263, 0.25373636],
       [0.49627472, 0.90028603, 0.36767173]])

In [ ]:
# Cria um valor aleatório, porém dentro de uma distribuição normalizada
np.random.randn()

7.054459437056067

### Exercícios de Numpy

#### Ex 1
Crie um array de 1 a 100 (incluso), e reforme ele para uma matriz de 10 x 10<br>
Bonus: Qual é a soma de cada linha?

In [119]:
arr = np.arange(1, 101, 1)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [120]:
arr[0]

np.int64(1)

In [121]:
# Reformulando a matrix para 10x10
arr = arr.reshape(10, 10)
arr[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
# Somando os valores de cada linha
# 0 soma por coluna
arr.sum(axis=1)

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

#### Ex 2
Crie uma matriz de 5x5 com valores de 0 a 24 e extraia:
- O elemento central
- A primeira coluna
- A última coluna

In [125]:
arr = np.arange(0, 25)
arr = arr.reshape(5, 5)

In [126]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [127]:
# Elemento central
arr[2, 2]

np.int64(12)

In [ ]:
# Primeira linha
arr[0]

array([0, 1, 2, 3, 4])

In [128]:
# Última coluna
arr[:, -1]

array([ 4,  9, 14, 19, 24])

#### Ex 3
Crie uma matriz de identidade 6x6 e multiplique tudo por 7<br>
Use np.eye() e multiplicação escalar

In [129]:
arr = np.eye(6, 6)

In [131]:
arr * 7

array([[7., 0., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0.],
       [0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 7.]])

#### Ex 4
Crie dois arrays randômicos de (3, 3):
- Some eles
- Multiplique cada elemento
- Faça o produto

In [133]:
arr1 = np.random.rand(3, 3)
arr2 = np.random.rand(3, 3)

In [139]:
print(f"""
    Array 1: \n{arr1}\n
    Array 2: \n{arr2}
    """)


    Array 1: 
[[0.63856294 0.28020572 0.85374113]
 [0.84744546 0.80050501 0.49972645]
 [0.73856246 0.21221363 0.66254262]]

    Array 2: 
[[0.4716879  0.52731576 0.76921693]
 [0.99712945 0.93440381 0.10838698]
 [0.42704641 0.81427699 0.63632765]]
    


In [140]:
arr1 + arr2

array([[1.11025084, 0.80752148, 1.62295806],
       [1.84457491, 1.73490882, 0.60811343],
       [1.16560887, 1.02649062, 1.29887027]])

In [141]:
arr1 * arr2

array([[0.30120241, 0.14775689, 0.65671213],
       [0.84501283, 0.74799493, 0.05416384],
       [0.31540045, 0.17280068, 0.42159419]])

In [142]:
np.dot(arr1, arr2)

array([[0.94519087, 1.29373135, 1.06482316],
       [1.41134327, 1.60178203, 1.05662347],
       [0.84291189, 1.12724206, 1.01271013]])

#### Ex 5
Crie um array 1D com 30 valores entre 0 e 1

In [143]:
arr = np.linspace(0, 1, 30)

In [146]:
arr

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [147]:
arr.shape

(30,)

#### Ex 6
Crie uma matriz 10x10 de randômicos (0 a 1) e substitua todos os valores maiores do que 0.5 com 1 e todos os menores do que 0.5 com 0

In [150]:
arr = np.random.rand(10, 10)

In [151]:
arr[arr > 0.5] = 1
arr[arr <= 0.5] = 0
arr

array([[0., 0., 1., 1., 1., 1., 1., 0., 0., 1.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 1., 1.],
       [0., 1., 1., 1., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 1., 0., 0., 1., 1., 0.],
       [1., 1., 0., 1., 0., 1., 1., 1., 0., 1.],
       [0., 1., 0., 1., 1., 0., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 1., 0., 1., 1., 1., 1., 1., 1., 0.]])

#### Ex 7
Criar uma matriz (4x4) e normalize ela (média = 0, std = 1)

#### Ex 8
Faça uma matriz 2D com forma (10, 5), achate para 1D e então reformate para (10, 5)

In [152]:
arr = np.full((10, 5), 7)

In [154]:
arr = arr.flatten()

In [156]:
arr = arr.reshape(10, 5)

#### Ex 9
Crie um ndarray de uma lista e depois transforme esse ndarray em lista novamente, depois crie uma ndarray zerado, exiba seu tamanho e forma.

In [4]:
lista = list([1, 2, 3])
arr = np.array(lista)

In [6]:
lista_cp = arr.tolist()
lista_cp

[1, 2, 3]

In [8]:
arr_zero = np.zeros((3, 4))
arr_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr.shape, arr.size

((3,), 3)

#### Ex 10
Problem: Create a 4x4 array with numbers 1 to 16. Extract the second row and the last column.
Theory: NumPy arrays support advanced indexing and slicing, similar to Python lists but extended to multiple dimensions. This is critical for selecting specific data in ML datasets.

In [ ]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
arr[2], arr[:, -1]

(array([ 9, 10, 11, 12]), array([ 4,  8, 12, 16]))

#### Ex 11
Problem: Create an array with random integers between 1 and 100 (size 10). Compute its mean and standard deviation.

In [18]:
arr = np.random.rand(1, 100).reshape(10, 10)
arr

array([[0.39259869, 0.98954485, 0.19851481, 0.63401907, 0.79625636,
        0.93190328, 0.41442661, 0.43374523, 0.38711875, 0.12728536],
       [0.02370322, 0.84227378, 0.32541449, 0.3073206 , 0.18536037,
        0.09839882, 0.37060565, 0.03982972, 0.43048399, 0.26649523],
       [0.10815658, 0.9790545 , 0.84823307, 0.35123908, 0.15643053,
        0.71796898, 0.91034725, 0.32671233, 0.64550332, 0.91242321],
       [0.64818088, 0.71812715, 0.91627903, 0.18668533, 0.26510987,
        0.60997087, 0.69186667, 0.32166732, 0.03690595, 0.28637276],
       [0.58323584, 0.09333445, 0.05966523, 0.29981089, 0.37187424,
        0.31505191, 0.49743923, 0.59795148, 0.96005643, 0.18893559],
       [0.51459689, 0.48494254, 0.4678087 , 0.07986803, 0.00992536,
        0.21822825, 0.55220261, 0.65730802, 0.13864836, 0.14754552],
       [0.18820164, 0.7820086 , 0.7216229 , 0.55535422, 0.69368942,
        0.85867424, 0.61947013, 0.76551678, 0.95604446, 0.90339764],
       [0.85568754, 0.02252991, 0.7862373

In [22]:
np.mean(arr), np.std(arr)

(np.float64(0.4613444699673534), np.float64(0.28246752882726883))

#### Ex 12
Problem: Create two 2x2 matrices, A = [[1, 2], [3, 4]] and B = [[5, 6], [7, 8]]. Perform matrix multiplication.

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [26]:
A @ B

array([[19, 22],
       [43, 50]])

#### Ex 13
Problem: Create an array with 10 random integers between 1 and 50. Find all elements greater than 30.

In [36]:
arr = np.random.randint(1, 50, size=10)

In [38]:
arr[arr > 30]

array([36, 45, 43, 34, 32])

#### Ex 14
Problem: Create two 1D arrays, a = [1, 2, 3] and b = [4, 5, 6]. Concatenate them into a single array.

In [40]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

np.concat((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

#### Ex 15
Problem: Create a 3x3 array with random integers between 1 and 10. Normalize each row by subtracting the row mean and dividing by the row standard deviation.

In [52]:
arr = np.random.randint(1, 10, size=(3, 3))

In [54]:
row_means = np.mean(arr, axis=1, keepdims=True)
row_std = np.std(arr, axis=1, keepdims=True)

normalized = (arr - row_means) / row_std

In [55]:
normalized

array([[ 0.70710678, -1.41421356,  0.70710678],
       [ 0.        ,  1.22474487, -1.22474487],
       [ 0.16222142,  1.13554995, -1.29777137]])

#### Ex 16
Problem: Create a 5x5 array with random integers between 0 and 100. Replace all values greater than the array’s median with the array’s maximum value.

In [76]:
arr = np.random.randint(0, 100, size=(5, 5))
arr

array([[27, 12, 26, 68, 29],
       [85, 62, 86, 76, 69],
       [29,  0, 51, 25, 98],
       [78, 48, 80, 21, 26],
       [28, 31, 42,  5,  1]])

In [78]:
np.median(arr)

np.float64(31.0)

In [79]:
arr[arr > np.median(arr)] = arr.max()
arr

array([[27, 12, 26, 98, 29],
       [98, 98, 98, 98, 98],
       [29,  0, 98, 25, 98],
       [98, 98, 98, 21, 26],
       [28, 31, 98,  5,  1]])

#### Ex 17
Problem: Create a 3x3 symmetric matrix (e.g., [[4, 2, 1], [2, 3, 2], [1, 2, 4]]). Compute its eigenvalues and eigenvectors.

In [83]:
arr = np.array([[4, 2, 1], [2, 3, 2], [1, 2, 4]])
eigenvalues, eigenvectors = np.linalg.eig(arr)

In [84]:
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: \n", eigenvectors)

Eigenvalues:  [7. 3. 1.]
Eigenvectors: 
 [[-5.77350269e-01 -7.07106781e-01  4.08248290e-01]
 [-5.77350269e-01 -4.62331560e-17 -8.16496581e-01]
 [-5.77350269e-01  7.07106781e-01  4.08248290e-01]]


#### Ex 17
Problem: Create two 3x2 arrays with random integers. Stack them horizontally to form a 3x4 array, then split the result into two 3x2 arrays again.

In [86]:
arr1 = np.random.rand(3, 2)
arr2 = np.random.rand(3, 2)

In [88]:
np.hstack((arr1, arr2))

array([[0.93296198, 0.32460707, 0.53616509, 0.80207297],
       [0.49831853, 0.96785495, 0.95608478, 0.17718263],
       [0.57220435, 0.83947683, 0.92424945, 0.59433301]])

In [90]:
np.hsplit(np.hstack((arr1, arr2)), 2)

[array([[0.93296198, 0.32460707],
        [0.49831853, 0.96785495],
        [0.57220435, 0.83947683]]),
 array([[0.53616509, 0.80207297],
        [0.95608478, 0.17718263],
        [0.92424945, 0.59433301]])]

#### Ex 18
Problem: Create a 4x4 array with random integers between 1 and 10. Compute the pairwise Euclidean distances between all rows without using loops.

In [ ]:
arr = np.random.randint(1, 10, size=(4, 4))

In [91]:
diff = arr[:, np.newaxis, :] - arr[np.newaxis, :, :]
distances = np.sqrt(np.sum(diff ** 2, axis=2))

In [96]:
# É interessante notar que cada array interno faz o cálculo de distância Euclidiana com cada outro array interno..
# Nota-se que os arrays internos quando calculada a distância entre ele mesmo, resulta em 0, pois os valores são iguais.
print(f"""
    Array Original: \n{arr}\n
    Distâncias: \n{distances}
    """)


    Array Original: 
[[4 2 1]
 [2 3 2]
 [1 2 4]]

    Distâncias: 
[[0.         2.44948974 4.24264069]
 [2.44948974 0.         2.44948974]
 [4.24264069 2.44948974 0.        ]]
    


## Estudos Mesclados
Nessa etapa eu uso o que foi aprendido em Pandas e em Numpy para manipular dados e realizar alguns processos

### Ex 1
Criar um array randômico com numpy, somar as colunas 0 e 1, colocar os valores normais em uma tabela pandas e em outra tabela, colocar os mesmos valores, porém normalizados.

In [135]:
data_array = np.random.randint(1, 100, size=(5, 5))
data_array

array([[60, 37, 21, 62, 99],
       [30, 83, 64, 70, 34],
       [55, 45,  4, 56, 82],
       [94, 87, 20, 62, 54],
       [69, 36, 55, 69, 73]])

In [136]:
# Soma dos valores da coluna 0 e 1
# Deletado a coluna inútil
data_array[:, 0] = data_array[:, 0:2].sum(axis=1)
data_array = np.delete(data_array, 1, axis=1)

In [137]:
data_pandas = pd.DataFrame(data_array)

In [ ]:
# Alterando os nomes dos indices da tabela
data_pandas.index = ['a', 'b', 'c', 'd', 'e'] # type: ignore

In [139]:
data_pandas

0   1   2   3
a   97  21  62  99
b  113  64  70  34
c  100   4  56  82
d  181  20  62  54
e  105  55  69  73

In [ ]:
# Aplicando a normalização nos dados
std_pandas, mean_pandas = data_pandas.std(), data_pandas.mean()
normalized = (data_pandas - mean_pandas) / std_pandas

In [141]:
data_pandas.max()

0    181
1     64
2     70
3     99
dtype: int64

In [143]:
# O ponto e vírgula corta a exibição do [none, none] no final
display(data_pandas), display(normalized);

0   1   2   3
a   97  21  62  99
b  113  64  70  34
c  100   4  56  82
d  181  20  62  54
e  105  55  69  73

0         1         2         3
a -0.632944 -0.462941 -0.312395  1.215953
b -0.176768  1.224047  1.076026 -1.366953
c -0.547411 -1.129890 -1.353710  0.540423
d  1.761979 -0.502173 -0.312395 -0.572213
e -0.404856  0.870957  0.902473  0.182790

### Ex 2
Create a NumPy array of shape (5, 3) filled with random integers from 1 to 100.
Convert it into a Pandas DataFrame with columns: "Math", "Science", "English".
Then, calculate the average score per subject.

In [2]:
arr = np.random.randint(1, 100, size=(5, 3))
arr

array([[37,  1, 36],
       [43, 26, 31],
       [90,  9, 30],
       [49,  5, 20],
       [ 2, 24, 70]])

In [6]:
arr_pandas = pd.DataFrame({
    "math": [arr[:, 0]],
    "science": [arr[:, 1]],
    "english": [arr[:, 2]]
})

In [12]:
arr_pandas['math_mean'] = np.mean(arr_pandas['math'].to_list())
arr_pandas['science_mean'] = np.mean(arr_pandas['science'].to_list())
arr_pandas['english_mean'] = np.mean(arr_pandas['english'].to_list())

In [13]:
arr_pandas

math            science               english  math_mean  \
0  [37, 43, 90, 49, 2]  [1, 26, 9, 5, 24]  [36, 31, 30, 20, 70]       44.2   

   science_mean  english_mean  
0          13.0          37.4

### Ex 3
Create a DataFrame with random ages (18–60) and salaries (30k–120k) for 10 people.
Use NumPy to generate the values

Use Pandas to create and describe the DataFrame

Add a new column "Tax" = 15% of salary.

In [19]:
arr_ages = np.random.randint(18, 60, size=10)
arr_salaries = np.random.randint(30000, 120000, size=10)

In [21]:
pandas_data = pd.DataFrame({
    "ages": arr_ages,
    "salary": arr_salaries
})
pandas_data['tax'] = pandas_data["salary"] * 0.15

In [22]:
pandas_data

ages  salary       tax
0    32  113949  17092.35
1    51   43593   6538.95
2    36   38188   5728.20
3    54  112454  16868.10
4    51  118259  17738.85
5    34  118027  17704.05
6    26  108137  16220.55
7    46   57169   8575.35
8    20   73634  11045.10
9    48  103294  15494.10

### Ex 4
Generate a NumPy datetime range for 10 consecutive days.
Convert it to a Pandas DatetimeIndex and set it as the index of a DataFrame containing random temperature data.

In [ ]:
# Criando um range de datas, do dia 01 ao 10
arr_date = np.arange('2023-01-01', '2023-01-11', dtype='datetime64[D]')

# Criando um array de valores entre 18 e 33
arr_temp = np.random.randint(18, 33, size=(10))

In [11]:
date = pd.DataFrame({
    'data': arr_date,
    'temperature': arr_temp
})

In [12]:
date

data  temperature
0 2023-01-01           23
1 2023-01-02           23
2 2023-01-03           22
3 2023-01-04           18
4 2023-01-05           23
5 2023-01-06           26
6 2023-01-07           24
7 2023-01-08           19
8 2023-01-09           32
9 2023-01-10           25

### Ex 5
Using a DataFrame with random exam scores (NumPy),
Add a column that shows whether the student passed each subject (True if score > 60, else False).

In [74]:
arr = np.array((np.random.beta(a=8, b=3, size=10).round(4) * 100))

In [ ]:
data = pd.DataFrame({
    'notas': arr,
    'aprovado': arr > 70
})

In [86]:
print(f"""
    A quantidade de aprovados é {data['aprovado'].loc[data['aprovado'] == True].count()}
    A quantidade de desaprovados é {data['aprovado'].loc[data['aprovado'] == False].count()}
""")


    A quantidade de aprovados é 8
    A quantidade de desaprovados é 2



### Ex 6
Create a 5x5 NumPy array with random integers, convert it to a DataFrame.
Label the rows as "A" to "E"

Label the columns as "V1" to "V5"

Calculate the mean and std deviation for each column using Pandas

In [87]:
arr = np.random.randint(1, 100, size=(5, 5))

In [91]:
data = pd.DataFrame(arr, index=['A', 'B', 'C', 'D', 'E'])

In [92]:
data.columns = ['V1', 'V2', 'V3', 'V4', 'V5']

In [95]:
data

V1  V2  V3  V4  V5
A  58  28  67   5  77
B  21   4  21  44  86
C  50  40  53  45  15
D   4  58  88  24  80
E   8  20  80  33  45

### Ex 7
Simulate sales data using NumPy:
Create arrays for 100 product names, prices, and quantities

Build a Pandas DataFrame from them

Add a column for "Total" = Price × Quantity

Filter all products where Total > 500

In [18]:
product_name = np.arange(1, 101)
product_price = np.random.rand(100) * 100
product_quantity = np.random.randint(100, 1000, size=(100))

In [19]:
data = pd.DataFrame({
    "name": product_name,
    "price": product_price,
    "quantity": product_quantity
})

In [21]:
data['total'] = data['price'] * data['quantity']

In [22]:
data['name'].loc[data['total'] > 500].count()

np.int64(98)

### Ex 8
Create a DataFrame of 20 people with random ages using NumPy.
Then:

Use .groupby() to group people by age range: <30, 30–50, >50

Compute the average age and count per group

In [ ]:

# We can use normal distribution (Gaussian) to generate the trend data.
names = ['Alice', 'Bob', 'Charlie', 'Diana', 'Eva', 'Frank', 'George', 'Hannah']
names = np.random.choice(names, size=100)
arr = np.random.normal(30, 5, 100)